// Auto-generated by build.rs

use actix_web::{get, web::ServiceConfig, HttpResponse, Responder};
use svc_dynamic_form_rust::controllers::rohan_controller::rohan as rohan_controller_rohan;
use svc_dynamic_form_rust::controllers::publication_controller::index as publication_controller_index;
use svc_dynamic_form_rust::controllers::research_controller::research as research_controller_research;
use svc_dynamic_form_rust::controllers::help_controller::help_h as help_controller_help_h;
use svc_dynamic_form_rust::controllers::help_controller::help_me as help_controller_help_me;
use svc_dynamic_form_rust::controllers::faq_controller::index as faq_controller_index;

#[get("/healthz")]

pub async fn health_check() -> impl Responder {
    HttpResponse::Ok()
        .json(serde_json::json!({ "status": "ok" }))
}

pub fn config(cfg: &mut ServiceConfig) {
    // Static route
    cfg.service(health_check);

    // AUTO-GENERATED ROUTES BELOW
    cfg.service(rohan_controller_rohan);
    cfg.service(publication_controller_index);
    cfg.service(research_controller_research);
    cfg.service(help_controller_help_h);
    cfg.service(help_controller_help_me);
    cfg.service(faq_controller_index);

}
